# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-31 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='logo_text.png', upload_to='')),
                ('description', models.TextField()),
                ('check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, default='msc.png', upload_to='')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('updatedtime', models.DateField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, default='guest', max_length=50)),
            ],
            options={
                'ordering': ['-updatedtime', '-timestamp'],
            },
        ),
    ]
